- name: Build APK
        working-directory: ./workspace/${{ github.event.inputs.subdir }}
        run: |
          set -e

          # 1) Download & extract compatible Gradle (used to generate wrapper)
          GRADLE_VER=7.5.1
          echo "Ensuring Gradle ${GRADLE_VER} is available..."
          mkdir -p $HOME/gradle
          curl -sSLo gradle.zip https://services.gradle.org/distributions/gradle-${GRADLE_VER}-bin.zip
          unzip -q gradle.zip -d $HOME/gradle
          rm gradle.zip

          # Add Gradle bin to PATH for the remainder of this step
          export PATH="$HOME/gradle/gradle-${GRADLE_VER}/bin:$PATH"

          # 2) Create wrapper with the compatible Gradle if wrapper not present
          if [ ! -f "gradlew" ]; then
            echo "gradlew not found — creating wrapper with Gradle ${GRADLE_VER}..."
            gradle wrapper --gradle-version ${GRADLE_VER}
          fi
          chmod +x gradlew

          # 3) Run build (same signing logic as before)
          if [[ "${{ github.event.inputs.taskName }}" == *Release* ]]; then
            echo "Task contains 'Release', attempting to sign a release build with a debug key."
            if [ ! -f "$HOME/.android/debug.keystore" ]; then
              echo "Debug keystore not found. Creating one..."
              keytool -genkey -v -keystore debug.keystore -storepass android \
                -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 \
                -dname "C=US, O=Android, CN=Android Debug"
              mkdir -p $HOME/.android
              mv debug.keystore $HOME/.android/debug.keystore
            fi

            ./gradlew ${{ github.event.inputs.taskName }} \
              -Pandroid.injected.signing.store.file="$HOME/.android/debug.keystore" \
              -Pandroid.injected.signing.store.password=android \
              -Pandroid.injected.signing.key.alias=androiddebugkey \
              -Pandroid.injected.signing.key.password=android \
              --stacktrace
          else
            ./gradlew ${{ github.event.inputs.taskName }} --stacktrace
          fi